version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./php/:/var/www/html/"
    ports:
      - "80:80"

  mysql-server:
    image: mysql:5
    restart: always
    environment:
      TZ: "Europe/Zurich"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: 'photoblog'
    volumes:
      - ./db/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8181:80"
volumes:
  mysql-data:
